[build]
  command = "npm i && cd api && npm i && npm run build && cd .. && CI=false npm run build && cp api/build/graphql-schema.js api/build/functions/graphql/. && cp api/build/schema.graphql api/build/functions/graphql/. && cd api/src/functions/graphql && npm i"
  publish = "build"
  functions = "api/build/functions"

[dev]
  command = "npm start"

[template.environment]
  NEO4J_URI = "Neo4j URI (ex: bolt://localhost:7687)"
  NEO4J_USER = "Neo4j User"
  NEO4J_PASSWORD = "Neo4j Password"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"  
    Vary = "Origin"
